name: "run tests"
on: push

jobs:
  execute-gut:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.0.3
          gut_params: -gdir=res://tests/ -gprefix=test_ -gsuffix=.gd -gexit -ginclude_subdirs

